---
# role: hosts
# file: tasks/main.yml

- name: HOSTS | Collect automatic host address information
  when: hosts_ip_all | bool or not hosts_ip_static | bool
  block:
    - name: HOSTS | Load platform packages
      ansible.builtin.include_vars: "{{ ansible_facts.os_family }}.yml"

    - name: HOSTS | Install address discovery tools
      become: true
      become_user: root
      ansible.builtin.package:
        name: "{{ __hosts_packages }}"
        state: present

    - name: HOSTS | Refresh network facts after installing address discovery tools
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - network

    - name: HOSTS | Read DHCP default routes for automatic address selection
      ansible.builtin.command:
        argv: [ip, -4, route, show, default, proto, dhcp]
      check_mode: false
      changed_when: false
      register: __hosts_dhcp_routes
      when: not hosts_ip_all | bool

- name: HOSTS | Write local host records
  become: true
  become_user: root
  ansible.builtin.template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
    backup: "{{ hosts_backup }}"
  notify: refresh hosts facts
